// Autogenerated from Pigeon (v10.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ToastApi {
  func toastMessage(message: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ToastApiSetup {
  /// The codec used by ToastApi.
  /// Sets up an instance of `ToastApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ToastApi?) {
    let toastMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ToastApi.toastMessage", binaryMessenger: binaryMessenger)
    if let api = api {
      toastMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        do {
          try api.toastMessage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toastMessageChannel.setMessageHandler(nil)
    }
  }
}
